// eslint-disable-next-line @typescript-eslint/no-unused-vars
const icons = [
  'analytics',
  'approved',
  'check',
  'clock',
  'close',
  'delete',
  'diagonal-arrow',
  'dropdown-arrow',
  'Google',
  'heart',
  'heart-filled',
  'hourglass',
  'log-in',
  'logout',
  'reject',
  'search',
  'smile',
  'user',
  'video',
  'logo',
  'logo-no-color',
  'tiktok',
  'x',
  'instagram',
  'quotation-mark',
  'add',
  'bucket',
  'letter',
  'boldCross',
  'menu',
  'upload',
  'edit',
  'microphone',
  'videocam-off',
  'microphone-off',
] as const;

export type IconName = (typeof icons)[number];
