import '@/styles/main.scss';
import type { Metadata } from 'next';

import { Montserrat_Alternates } from 'next/font/google';

const montserratAlternates = Montserrat_Alternates({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['cyrillic', 'latin', 'cyrillic-ext'],
  display: 'swap',
  variable: '--montserrat-alternates',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserratAlternates.className}>
      <body>{children}</body>
    </html>
  );
}
